baseURL = 'https://example.org/'
locale = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Quotes'
    pageRef = '/quotes/'
    identifier = 'quotes'
    weight = 1

  [[menus.main]]
    name = 'Musings'
    pageRef = '/musings/'
    identifier = 'musings'
    weight = 2

[module]
  [module.hugoVersion]
    extended = false
    min = '0.93.0'

